apps/auth_login/urls.py
from django.urls import path
from .view.views import *

app_name = 'auth'

urlpatterns = [
    path('login/', AuthLoginView.as_view(), name='login'),
    path('logout/', AuthLogoutView.as_view(), name='logout'),
    path('signup/', AuthSignupView.as_view(), name='signup')
]

apps/courier/urls.py
from django.urls import path
from .view.views import *

app_name = 'courier_app'

urlpatterns = [
    path('', Courier.as_view(), name='courier')
]

apps/customer/urls.py
from django.urls import path
from .view.views import *
app_name = 'customer_app'

urlpatterns = [
    path('', Customer.as_view(), name='customer'),
    # path('profile/', Profile.as_view(), name='profile'),
    path('profile/<int:pk>/', Profile.as_view(), name='profile_id')
]

apps/home/urls.py
from django.urls import path
from .view.views import *

app_name = 'delivery'

urlpatterns = [
    path('', Home.as_view(), name='home'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static


def redirect_function(request):
    return redirect('/home')


urlpatterns = [
    path('', redirect_function),
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),
    path('home/', include('apps.home.urls')),
    path('courier/', include('apps.courier.urls')),
    path('customer/', include('apps.customer.urls')),
    path('auth/', include('apps.auth_login.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/auth_login/models.py
from django.db import models

# Create your models here.

apps/courier/models.py
from django.db import models

# Create your models here.

apps/customer/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(
        upload_to='customer/avatars/', blank=True, null=True)

    def __str__(self) -> str:
        return self.user.get_full_name()

apps/home/models.py
from django.db import models

# Create your models here.

apps/auth_login/view/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.views.generic import FormView
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import login
# from django.contrib.auth.models import User
from ..form import *
# Create your views here.


class AuthLoginView(LoginView):
    next_page = reverse_lazy('delivery:home')
    template_name = 'login.html'
    title = 'Login'
    form_class = FormsAuthentication

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(self.next_page)
        return super().dispatch(request, *args, **kwargs)

    def get_redirect_url(self) -> str:
        return super().get_redirect_url()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        return context


class AuthLogoutView(LogoutView):
    next_page = reverse_lazy('auth:login')
    template_name = 'login.html'


class AuthSignupView(FormView):
    template_name = 'signup.html'
    form_class = AuthForms
    success_url = reverse_lazy('delivery:home')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(reverse_lazy('delivery:home'))
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Signup'
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            user = form.save(commit=False)
            user.username = form['email'].data
            user.save()
            # login(request, user,
            #       backend='django.contrib.auth.backends.ModelBackend')
            return HttpResponseRedirect(self.success_url, *args, **kwargs)
        else:
            context = self.get_context_data(**kwargs)
            context['error'] = form.errors.values()
            return render(request, self.template_name, context)

apps/courier/view/views.py
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


@method_decorator(login_required, name='dispatch')
class Courier(TemplateView):
    template_name = 'courier.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Courier'
        return context

apps/customer/view/views.py
from django.views.generic import TemplateView, UpdateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from ..form import *
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import update_session_auth_hash


@method_decorator(login_required, name='dispatch')
class Customer(TemplateView):
    template_name = 'customer.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Customer'
        return context


@method_decorator(login_required, name='dispatch')
class Profile(UpdateView):
    model = User
    template_name = 'profile.html'
    form_class = CustomerForm
    success_url = reverse_lazy('customer_app:profile_id')

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def changePassword(self):
        pass

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if request.POST['action'] == 'change_password':
            change_form = PasswordChangeForm(request.user, form.data)
            if change_form.is_valid():
                print('valid')
                user = change_form.save()
                update_session_auth_hash(request, user)
        else:
            form_product = BasigCustomerForm(
                request.POST, request.FILES, instance=request.user.customer)
            data = {}
            if form.is_valid() and form_product.is_valid():
                data = form.save()
                form_product.save()
            else:
                data['error'] = form.errors
        return HttpResponseRedirect(reverse_lazy('customer_app:profile_id', kwargs={'pk': request.user.id}))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = CustomerForm(instance=self.request.user)
        form_customer = BasigCustomerForm(instance=self.request.user.customer)
        password_form = PasswordChangeForm(self.request.user)
        context['title'] = 'Profile'
        context['form_customer'] = form_customer
        context['form'] = form
        context['password_form'] = password_form
        return context

apps/home/view/views.py
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


@method_decorator(login_required, name='dispatch')
class Home(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Home'
        return context

apps/auth_login/templates/login.html
{% extends 'component/body.html' %}
{% load widget_tweaks %}

{% block body %}
<div class="login-box w-25 mx-auto mt-5 bg-dark rounded-3">
    <div class="card card-outline card-primary bg-dark shadow-sm rounded-3">
        <div class="card-header text-center text-light">
            <a href="{% url 'customer_app:customer' %}" class="h1 text-light text-decoration-none">
                <b>{% if request.GET.next != '/courier/' %}Customer{% else %}Courier{% endif %}</b>
            </a>
        </div>
        <div class="card-body text-light">
            <p class="login-box-msg">
                {% if request.GET.next != '/courier/' %}Customer{% else %}Courier{% endif %}
            </p>
            <form action="." method="post">
                {% csrf_token %}
                <input type="hidden" value="{{next}}" name="next">
                <div class="input-group mb-3">
                    {% render_field form.username|add_class:'form-control'|attr:'autofocus:on' placeholder=form.username.label %}
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="bi bi-person-circle"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    {{form.password|add_class:'form-control'|attr:'placeholder=password'}}
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="bi bi-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="row p-2">
                    <div class="col-12 d-flex p-1">
                        <button type="submit" class="btn btn-primary btn-block w-100 mx-auto">
                            <i class="bi bi-send-fill"></i>
                            Sign In
                        </button>
                    </div>
                </div>
                <p class="mb-1">
                    <a href="#" class="text-light text-decoration-none">I forgot my password</a>
                </p>
                <p class="mb-0">
                    <a href="{% url 'auth:signup' %}" class="text-center text-light text-decoration-none">Register a new
                        membership</a>
                </p>
                <a href='{% url "social:begin" "facebook" %}'
                    class="btn btn-outline-primary btn-block w-100 mt-2">Sign in with Facebook</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

apps/auth_login/templates/signup.html
{% extends 'component/body.html' %}
{% load widget_tweaks %}

{% block body %}
<div class="login-box w-25 mx-auto mt-5 bg-dark rounded-3">
    <div class="card card-outline card-primary bg-dark shadow-sm rounded-3">
        <div class="card-header text-center text-light">
            <a href="{% url 'customer_app:customer' %}" class="h1 text-light text-decoration-none">
                <b>{% if request.GET.next != '/courier/' %}Customer{% else %}Courier{% endif %}</b>
            </a>
        </div>
        <div class="card-body text-light">
            <p class="login-box-msg">
                {% if request.GET.next != '/courier/' %}Customer{% else %}Courier{% endif %}
            </p>
            <form action="." method="post">
                {% csrf_token %}
                {% for field in form %}
                <div class="input-group mb-3">
                    <!-- <label for="id_{{field.name}}" class="form-label" >{{field.name}}</label> -->
                    {% render_field field|add_class:'form-control'|attr:'autofocus:on' placeholder=field.label %}
                </div>
                {% endfor %}
                {% if error %}
                <ul>
                    {% for e in error %}
                        {{e}}
                    {% endfor %}
                </ul>
                {% endif %}
                <div class="row p-2">
                    <div class="col-12 d-flex p-1">
                        <button type="submit" class="btn btn-primary btn-block w-100 mx-auto">
                            <i class="bi bi-send-fill"></i>
                            Sign In
                        </button>
                    </div>
                </div>
            </form>
            <p class="mb-0">
                <a href="{% url 'auth:login' %}" class="text-center text-light text-decoration-none">Login</a>
            </p>
        </div>
    </div>
</div>
{% endblock %}

apps/auth_login/templates/welcome_email_template.html
Hi {{ name }}

We're so excited to have you join us!

Nelson Borrego

apps/courier/templates/courier.html
{% extends 'component/body.html' %}

apps/customer/templates/customer.html
{% extends 'component/body.html' %}
{% load static %}

{% block body %}
<div class="container-fluid bg-dark mt-5 pt-3 pb-3 w-75">
    <div class="row">
        <div class="col-lg-4">
            <div class="text-center">
                <img src="{% if request.user.customer.avatar %}{{ request.user.customer.avatar.url }}{% else %}{% static 'img/avatar.png' %}{% endif %}" alt="Avatar" class="rounded-circle mb-2" width="100px"
                    height="100px">
                <p>{{request.user.get_full_name}}</p>
                <p class="text-secondary">{{ request.user.email }}</p>
                <ul class="list-group">
                    <li class="list-group-item list-group-item-action"><a href="#"
                            class="text-dark text-decoration-none">Create a Job</a></li>
                    <li class="list-group-item list-group-item-action"><a href="#"
                            class="text-dark text-decoration-none">My Jobs</a></li>
                    <li class="list-group-item list-group-item-action"><a
                            href="{% url 'customer_app:profile_id' request.user.id %}"
                            class="text-dark text-decoration-none">Profile Information</a></li>
                    <li class="list-group-item list-group-item-action"><a href="#"
                            class="text-dark text-decoration-none">Payments Detail</a></li>
                </ul>
            </div>
        </div>
        <div class="col-lg-8">
            {% block main %}{% endblock %}
        </div>
    </div>
</div>
{% endblock %}

apps/customer/templates/profile.html
{% extends 'customer.html' %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block main %}
<b class="text-secondary text-light">Basic Information</b>
<div class="card mt-2 mb-2">
    <div class="card-body">
        <form action="." method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form label_class='text-dark fs-4 my-1' %}
            {% bootstrap_form form_customer field_class='text-dark' label_class='text-dark fs-4 my-1' %}
            <input type="hidden" name="action" id="update_profile">
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>
<div class="card mt-2 mb-2">
    <div class="card-body">
        <form action="." method="POST" id="form_change">
            {% csrf_token %}
            {% bootstrap_form password_form label_class='text-dark fs-4 my-1' %}
            <input type="hidden" name="action" value="change_password">
            <button type="submit" class="btn btn-primary" id="change_password">Save</button>
        </form>
    </div>
</div>

{% endblock %}

apps/home/templates/home.html
{% extends 'component/body.html' %}

{% block body %}
<div class="row m-0 w-75 mx-auto my-5">
    <div class="col-lg-12 mb-3">
        <h1 class="text-center mt-5 mb-5">Welcome to fast parcel</h1>
    </div>
    <div class="col-lg-6">
        <div class="card bg-dark shadow-lg">
            <div class="card-body text-light">
                <h5 class="card-title">Customer</h5>
                <p class="card-text">
                    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Mollitia rem tenetur sed
                    alias architecto, aspernatur atque, dicta eligendi molestiae ipsum eius ullam ducimus ab minus.
                    Neque quasi sint eius fuga.
                </p>
                <a href="{% url 'customer_app:customer' %}" class="btn btn-primary">Details</a>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="card bg-dark shadow-lg">
            <div class="card-body text-light">
                <h5 class="card-title">Courier</h5>
                <p class="card-text">
                    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Mollitia rem tenetur sed
                    alias architecto, aspernatur atque, dicta eligendi molestiae ipsum eius ullam ducimus ab minus.
                    Neque quasi sint eius fuga.
                </p>
                <a href="{% url 'courier_app:courier' %}" class="btn btn-dark bg-primary shadow">Details</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}